### Drawing images and shapes using OpenCv
Let's start off by making a black square

### to draw an image we need to create a black or white image
by 

np.zeros((dimensions), np.uint8) ----># we can create black box

n.ones((dimensions), np.uint8) ------># we can create white image

In [5]:
import cv2
import numpy as np
#Create a black image
# 3 means three layers for RGB color
image = np.zeros((512, 512, 3), np.uint8)

#Can we make this in black and white?
image_bw = np.zeros((512, 512), np.uint8)

cv2.imshow('Black Rectangel(color)', image)
cv2.imshow('Black Retangle (B & W)', image_bw)
cv2.waitKey()
cv2.destroyAllWindows()

# Line

### cv2.line(image, starting cordinates, ending cordinates, color, thickness)

#### Draw a line over our black square

In [1]:
import numpy as np
import cv2
image = np.zeros((512, 512, 3), np.uint8)
cv2.line(image, (0, 0), (512, 512), (255, 127, 0), 5)
cv2.imshow('Blue Line', image)
cv2.waitKey()
cv2.destroyAllWindows()

# Rectangle

### rectange(image, starting vertex, opposite vertex, color, thickness)

In [3]:
image = np.ones((512, 512, 3), np.uint8)
cv2.rectangle(image,(100, 100), (300, 250), (127, 50, 127), 3)
cv2.imshow('Rectangle', image)
cv2.waitKey()
cv2.destroyAllWindows()

##### ^if you want to fill the rectangle with passed color the pass the thickness = -1

# Circle

### cv2.circle(image, center, radius, color, thickness)

In [9]:
image = np.ones((512, 512, 3), np.uint8)
cv2.circle(image, (256, 256), (50), (255, 2, 255), -3)
cv2.imshow('Circle', image)
cv2.waitKey()
cv2.destroyAllWindows()

# polylines
by this we can create triange, polygon, hexagon, ocatve etc...

### polylines(img, pts, isClosed, color, thickness)

## Polygons

In [2]:
import numpy as np, cv2
image = np.zeros((512, 512, 3), np.uint8)
#Let's define for point
pts = np.array([[10, 50], [400, 50], [90, 200], [50, 500]], np.int32)
print(f'Before reshape {pts}')
#Let's nw reshape our pints in form requred by polylines
pts = pts.reshape((-1, 1, 2))
print(f'After reshape {pts}')
cv2.polylines(image, [pts], True, (0, 0, 255), 3)
cv2.imshow('Polygon', image)
cv2.waitKey()
cv2.destroyAllWindows()

Before reshape [[ 10  50]
 [400  50]
 [ 90 200]
 [ 50 500]]
After reshape [[[ 10  50]]

 [[400  50]]

 [[ 90 200]]

 [[ 50 500]]]


# Trinangle

#### EXCERCISE

In [8]:
image = np.zeros((512, 512, 3), np.uint8)
#Let's define for pints
pts = np.array([[1, 509], [254, 1], [509, 509]], np.int32)
#Let's nw reshape our pints in form requred by polylines
pts = pts.reshape((-1, 1, 2))
cv2.polylines(image, [pts], True, (0, 0, 255), 3)
cv2.rectangle(image, (127, 255), (381, 509), (0, 255, 0), -3)
cv2.circle(image, (254, 382), (127), (255, 0, 0), -4)
cv2.putText(image, 'Noushad Khan', (134, 389), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 3)
cv2.imshow('Project', image)
cv2.waitKey()
cv2.destroyAllWindows()

# Text

### cv2.putText(image, 'Text to display', bottom left starting point, Font Type, Font Size, Color, thickness)

## Font style
FONT_HERSHEY_SIMPLEX, FONT_HERSHEY_PLAIN
FONT_HERSHEY_DUPLEX, FONT_HERSHEY_COMPLEX
FONT_HERSHEY_TRIPLEX, FONT_HERSHEY_COMPLEX_SMALL
FONT_HERSHEY_SCRIPT_SIMPLEX
FONT_HERSHEY_SCRIPT_COMPLEX

In [3]:
import cv2, numpy as np
image = np.ones((512, 512, 3), np.uint8)
cv2.putText(image, 'Noushad Khan', (134, 389), cv2.FONT_HERSHEY_SCRIPT_SIMPLEX, 1, (255, 255, 255), 3)
cv2.imshow('Text', image)
cv2.waitKey()
cv2.destroyAllWindows()